### ISSUE TITLE
PIXA_BAY_KEY

### ISSUE THREAD

**Issue by paul8909** [jvmachadorj/instagram-telegram-bot#1]
Hello,Very interesting idea, but I have a problem ...
When I run: 
raise UndefinedValueError('{} not found. Declare it as envvar or define a de
fault value.'.format(option))
decouple.UndefinedValueError: PIXA_BAY_KEY not found. Declare it as envvar or de
fine a default value.
What should I call the file with settings?
use python 3.7.3 on windows
ps. try 3.6.5 no change

**Comment by paul8909** [comment]
okay, I start it on windows add settings.ini
baut now another error
`https://pixabay.com/get/ed35b80d2ef2073ed1584d05fb1d4794e372e2dd11b10c4090f5c579
a2e9b4bcd1_1280.jpg
19
<Response [401]>
Traceback (most recent call last):
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\delegate.
py", line 88, in wait_loop
    await helper._invoke(j.on_message, msg)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 16, in _invoke
    return await fn(*args, **kwargs)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 191, in augmented
    return await _invoke(handler, msg)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 16, in _invoke
    return await fn(*args, **kwargs)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 269, in on_message
    await self._router.route(msg)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 244, in route
    return await _invoke(fn, msg, *args, **kwargs)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 16, in _invoke
    return await fn(*args, **kwargs)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 24, in d
    return await _invoke(method, *a, **kw)
  File "C:\Program Files\Python36\myvenv\lib\site-packages\telepot\aio\helper.py
", line 16, in _invoke
    return await fn(*args, **kwargs)
  File "C:\Program Files\Python36\myvenv\Scripts\telegram_bot.py", line 81, in o
n_chat_message
    await self._propose()
  File "C:\Program Files\Python36\myvenv\Scripts\telegram_bot.py", line 71, in _
propose
    image = download_photo()
  File "C:\Program Files\Python36\myvenv\Scripts\upload_photos.py", line 77, in
download_photo
    image = save_to_db(result, path, url)
  File "C:\Program Files\Python36\myvenv\Scripts\upload_photos.py", line 156, in
 save_to_db
    caption = create_random_caption(tags)
  File "C:\Program Files\Python36\myvenv\Scripts\upload_photos.py", line 140, in
 create_random_caption
    treated_tags = treat_tags(tags)
  File "C:\Program Files\Python36\myvenv\Scripts\upload_photos.py", line 124, in
 treat_tags
    result = json.loads(request.text)['data']
KeyError: 'data'`
and it reaction on message in the bot

**Comment by jvmachadorj** [comment]
You should use a file called .env with all environment variables
