### ISSUE TITLE
401 "Unauthorized" Error

### ISSUE THREAD

**Issue by drdoof2019** [jvmachadorj/instagram-telegram-bot#9]
Hello,
when I run the program it gives:
```
Fail to import moviepy. Need only for Video upload.
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Listening ...
Traceback (most recent call last):
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/loop.py", line 31, in run_forever
    allowed_updates=allowed_updates)
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/__init__.py", line 587, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/__init__.py", line 78, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/api.py", line 146, in request
    return await _parse(r)
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/api.py", line 129, in _parse
    raise e(description, error_code, data)
telepot.exception.UnauthorizedError: ('Unauthorized', 401, {'ok': False, 'error_code': 401, 'description': 'Unauthorized'})
Traceback (most recent call last):
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/loop.py", line 31, in run_forever
    allowed_updates=allowed_updates)
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/__init__.py", line 587, in getUpdates
    return await self._api_request('getUpdates', _rectify(p))
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/__init__.py", line 78, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/api.py", line 146, in request
    return await _parse(r)
  File "/home/sule/Masaüstü/igtelbottry/instagram-telegram-bot/venv/lib/python3.6/site-packages/telepot/aio/api.py", line 129, in _parse
    raise e(description, error_code, data)
telepot.exception.UnauthorizedError: ('Unauthorized', 401, {'ok': False, 'error_code': 401, 'description': 'Unauthorized'})
```

by the way example env file contains:

> TAGS_ID = 'rekite client id'

but I don't know what is that. is it my problem?

**Comment by drdoof2019** [comment]
I changed my telegram api code I think that was the problem. Now, program says Listening... and keeps waiting.

```
Fail to import moviepy. Need only for Video upload.
Request return 429 error!
{'message': 'Please wait a few minutes before you try again.', 'status': 'fail'}
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Listening ...
```
waited for 10 min and nothing happened

**Comment by jvmachadorj** [comment]
Hello @drdoof2019 

There is a mispelling word right there, It is `RiteKit Client ID` you can find it here https://ritekit.com/developer/dashboard/

I've updated de Readme file to add where to get this credentials.

RiteKit is an open api to generate hashtags based on some text. So that's why it is a project dependecy. I've also refactored the code so it is a bit more clear and exclude some unused code.

My next steps are to make this bot scalable and do a package for it. If you have any questions please don't hesitate to contact me

**Comment by jvmachadorj** [comment]
@drdoof2019 Actually I was looking in the documents for the main package I was using and actually it is not supported anymore
